- id: primary-influxdb_grafana
  type: group
  role: [primary-influxdb_grafana]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - cluster-haproxy
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

- id: influxdb_grafana
  type: group
  role: [influxdb_grafana]
  tasks: *common_tasks
  required_for: [deploy_end]
  requires: [deploy_start, primary-influxdb_grafana]
  parameters:
    strategy:
      type: parallel

- id: influxdb-firewall
  type: puppet
  groups: [primary-influxdb_grafana, influxdb_grafana]
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: "puppet/manifests/firewall.pp"
    puppet_modules: "puppet/modules"
    timeout: 360

- id: influxdb-cluster
  type: puppet
  groups: [primary-influxdb_grafana, influxdb_grafana]
  required_for: [cluster-haproxy]
  requires: [influxdb-firewall]
  parameters:
    puppet_manifest: "puppet/manifests/cluster.pp"
    puppet_modules: "puppet/modules"
    timeout: 360

- id: influxdb-vip
  type: puppet
  groups: [primary-influxdb_grafana, influxdb_grafana]
  required_for: [deploy_end]
  requires: [influxdb-cluster]
  parameters:
    puppet_manifest: "puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600

- id: influxdb-haproxy
  type: puppet
  groups: [primary-influxdb_grafana, influxdb_grafana]
  required_for: [deploy_end]
  requires: [cluster-haproxy, influxdb-vip]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: "puppet/modules"
    timeout: 3600

- id: influxdb-hiera
  type: puppet
  groups: [primary-influxdb_grafana, influxdb_grafana]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: "puppet/manifests/hiera.pp"
    puppet_modules: "puppet/modules"
    timeout: 120
