# Groups definitions
- id: primary-influxdb_grafana
  type: group
  version: 2.0.0
  role: [primary-influxdb_grafana]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
    - influxdb-hiera
    - influxdb-firewall
    - influxdb-cluster
    - influxdb-cluster-haproxy
    - influxdb-vip
    - influxdb-haproxy
    - influxdb-installation
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one

- id: influxdb_grafana
  type: group
  version: 2.0.0
  role: [influxdb_grafana]
  tasks: *common_tasks
  requires: [deploy_start, primary-influxdb_grafana]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: parallel

# Tasks definitions for the deployment
######################################

- id: influxdb-hiera
  type: puppet
  version: 2.0.0
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: "puppet/manifests/hiera.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: influxdb-firewall
  type: puppet
  version: 2.0.0
  requires: [netconfig]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/firewall.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: influxdb-cluster
  type: puppet
  version: 2.0.0
  requires: [influxdb-firewall]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/cluster.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: influxdb-cluster-haproxy
  type: puppet
  version: 2.0.0
  requires: [influxdb-cluster]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/cluster-haproxy.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: influxdb-vip
  type: puppet
  version: 2.0.0
  requires: [influxdb-cluster]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "/etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp"
    puppet_modules: /etc/puppet/modules
    timeout: 600

- id: influxdb-haproxy
  type: puppet
  version: 2.0.0
  requires: [influxdb-cluster-haproxy, influxdb-vip]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/haproxy.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: influxdb-installation
  type: puppet
  version: 2.0.0
  requires: [influxdb-haproxy]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: "puppet/manifests/influxdb.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

# Tasks definitions for the post-deployment
###########################################

- id: influxdb-enable-quorum
  type: puppet
  version: 2.0.0
  role: [primary-influxdb_grafana]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/enable_quorum.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: influxdb-configuration
  type: puppet
  version: 2.0.0
  role: [primary-influxdb_grafana]
  requires: [post_deployment_start]
  # We use upload_nodes_info as an anchor to order the post-deployment tasks executed
  # by this plugin and the LMA collector plugin. The dependency chain is:
  # influxdb-configuration -> upload_nodes_info -> (LMA collector tasks)
  required_for: [post_deployment_end, upload_nodes_info]
  parameters:
    puppet_manifest: "puppet/manifests/influxdb_configuration.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: grafana-mysql-provisioning
  type: puppet
  version: 2.0.0
  role: [primary-influxdb_grafana]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: "puppet/manifests/grafana_mysql.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: grafana-installation
  type: puppet
  version: 2.0.0
  role: [primary-influxdb_grafana, influxdb_grafana]
  requires: [post_deployment_start, grafana-mysql-provisioning]
  required_for: [post_deployment_end]
  # The cross-depends parameter is required because the Grafana installation
  # should only happen once the MySQL database has been provisioned.
  cross-depends:
    - name: grafana-mysql-provisioning
      role: [primary-influxdb_grafana]
  parameters:
    puppet_manifest: "puppet/manifests/grafana.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600

- id: grafana-configuration
  type: puppet
  version: 2.0.0
  role: [primary-influxdb_grafana]
  requires: [post_deployment_start, grafana-installation]
  # See comment above regarding the upload_nodes_info dependency
  required_for: [post_deployment_end, upload_nodes_info]
  parameters:
    puppet_manifest: "puppet/manifests/grafana_configuration.pp"
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
